# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 578617130189c480a0e62641fe064df9822db758b4ed2ad73d90f669c3ee5dbf4f342ddf211d6bc307d67404950ab7c7babfcd7c5ec63d94cd51e32fbeb19bc7

test:
  secret_key_base: 858da65accc1aa53b92fbf890e81636b2fd35ad5eca83ac2fbb1a8749c7e42a8bba7607a4f4a50ee90f95571abc4b097157cdb9743d37b2fd082167e0f2e9db2

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
